### ISSUE TITLE
`verify_checksum` does not work

### ISSUE THREAD

**Issue by briedel** [globus/globus-sdk-python#212] opened 2017-05-22 16:18 UTC
When setting `verify_checksum = True` in `TransferData`, the online transfer interface does not include that in that in the transfer settings:

![screen shot 2017-05-22 at 11 18 25](https://cloud.githubusercontent.com/assets/1161238/26318326/682dad64-3ee0-11e7-83ee-8a659bab4853.png)

**Comment by jaswilli** [comment] 2017-05-22 16:36
I'm not able to reproduce this. Can you provide an example where `verify_checksum=True` isn't working?

**Comment by sirosen** [comment] 2017-05-22 16:38
Please make sure you're setting `verify_checksum` as a key in the TransferData, not an attribute.
i.e. `tdata = TransferData(...); tdata['verify_checksum'] = True` rather than `tdata.verify_checksum = True`

The web UI sets it to true in all scenarios, IIRC.

**Comment by briedel** [comment] 2017-05-22 17:11
In my code I do:
```
        tdata = globus_sdk.TransferData(tc,
                                        config["origin"]["endpoint"],
                                        config["destination"][
                                            "endpoint"][endpoint],
                                        verify_checksum=True,
                                        sync_level="checksum")
      # add items here
      transfer_result = tc.submit_transfer(tdata)
```
Printing out `tdata` gives:
```
{'submission_id': u'1bb0ac81-3f11-11e7-bd15-22000b9a448b', 'preserve_timestamp': False, 'DATA_TYPE': 'transfer', 'DATA': [{'destination_path': '/home/s/spt/spt3g_backup/20170521.tar', 'source_path': '/buffer/3g_verified/20170521.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170510.tar', 'source_path': '/buffer/3g_verified/20170510.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170511.tar', 'source_path': '/buffer/3g_verified/20170511.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170512.tar', 'source_path': '/buffer/3g_verified/20170512.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170513.tar', 'source_path': '/buffer/3g_verified/20170513.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170514.tar', 'source_path': '/buffer/3g_verified/20170514.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/bolodata_short_2017.tar', 'source_path': '/buffer/3g_verified/bolodata_short_2017.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170515.tar', 'source_path': '/buffer/3g_verified/20170515.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170516.tar', 'source_path': '/buffer/3g_verified/20170516.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170517.tar', 'source_path': '/buffer/3g_verified/20170517.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170518.tar', 'source_path': '/buffer/3g_verified/20170518.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170519.tar', 'source_path': '/buffer/3g_verified/20170519.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}, {'destination_path': '/home/s/spt/spt3g_backup/20170520.tar', 'source_path': '/buffer/3g_verified/20170520.tar', 'recursive': False, 'DATA_TYPE': 'transfer_item'}], 'encrypt_data': False, 'sync_level': 3, 'source_endpoint': u'bf3baba0-ccef-11e6-9c84-22000a1e3b52', 'destination_endpoint': u'9cd89cfd-6d04-11e5-ba46-22000b92c6ec', 'verify_checksum': True}
```
and from `transfer_result`

```
{
  "submission_id": "1bb0ac81-3f11-11e7-bd15-22000b9a448b",
  "code": "Accepted",
  "resource": "/transfer",
  "task_id": "1bb0ac80-3f11-11e7-bd15-22000b9a448b",
  "DATA_TYPE": "transfer_result",
  "request_id": "BU1iD7z3I",
  "message": "The transfer has been accepted and a task has been created and queued for execution",
  "task_link": {
    "href": "task/1bb0ac80-3f11-11e7-bd15-22000b9a448b?format=json",
    "resource": "task",
    "rel": "related",
    "DATA_TYPE": "link",
    "title": "related task"
  }
}
```

Now checking `"task_id": "1bb0ac80-3f11-11e7-bd15-22000b9a448b"` on the website:

![screen shot 2017-05-22 at 12 11 02](https://cloud.githubusercontent.com/assets/1161238/26320264/d4d5dbec-3ee7-11e7-9f5a-c5bdb89c4b92.png)

**Comment by jaswilli** [comment] 2017-05-22 18:28
@briedel I think we figured it out. We found a policy setting for Endpoints where the admin can disable `verify_checksum` and sure enough, the destination endpoint in your transfer (`NERSC#HPSS`) has `verify_checksum` disabled.

**Comment by briedel** [comment] 2017-05-22 18:45
Odd. Why does `sync_level 3` work then, isn't that basically the same thing?

**Comment by karlito-go** [comment] 2017-05-22 20:04
sync level 3 is not affected by the endpoint's verify_checksum setting.   sync levels are usually chosen explicitly by the user (and not the default), so we didn't think the endpoint needed to override that.   in contrast, verify_checksum (after transfer) is the web UX default.

**Comment by jaswilli** [comment] 2017-05-22 20:53
I'm going to close this but feel free to re-open if there's more to discuss.

**Closed by jaswilli** 2017-05-22 20:53 UTC
